[package]
name = "kiwi-lang"
version = "0.1.0"
authors = ["litala123 <litala@rpi.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"

[dev-dependencies]
test-case = "1.1.0"
